import { Selector } from 'testcafe';

// Page Elements
const signButton = Selector('.login')
const logEmail = Selector('#email')
const logPassword = Selector('#passwd')
const login = Selector("#SubmitLogin")
const email = Selector('#email_create')
const createButton = Selector('#SubmitCreate')
const radioButton = Selector('#id_gender1')
const customFirstName = Selector('#customer_firstname')
const customLastName = Selector('#customer_lastname')
const confirmEmail = Selector('#email')
const password = Selector('#passwd')
const days = Selector('#days')
const months = Selector('#months')
const years = Selector('#years')
const news = Selector('#newsletter')
const offers = Selector('#optin')
const firstname = Selector('#firstname')
const lastname = Selector('#lastname')
const company = Selector('#company')
const address1 = Selector('#address1')
const address2 = Selector('#address2')
const city = Selector('#city')
const state = Selector('#id_state')
const postCode = Selector('#postcode')
const country = Selector('#id_country')
const other = Selector('#other')
const phone = Selector('#phone')
const phoneMobile = Selector('#phone_mobile')
const alias = Selector('#alias')
const registerButton = Selector('#submitAccount')
const logOut = Selector('.logout')

fixture `Sign in Test`
    .page `http://automationpractice.com/index.php`

test('New test 1', async t => {
    await t
        .click(signButton)
        .takeScreenshot()
        .typeText(email,"alejandro.gomez@rpag.com")
        /*.typeText(password,"Test@1234")*/
        .click(createButton)
        .takeScreenshot()
        .click(radioButton)
        .typeText(customFirstName,"Alejandro")
        .typeText(customLastName,"Gomez")
        .expect(confirmEmail.value).contains('alejandro.gomez@rpag.com')
        .typeText(password,"alejo123")
        .click(days)
        .click(Selector ('option').filter('[value="16"]'))
        .expect(days.value).eql('16')
        .click(months)
        .click(months.find('option').withText('February'))
        //.expect(months.value).eql('February')
        .click(years)
        .click(Selector ('option').filter('[value="1994"]'))
        .expect(years.value).eql('1994')
        .click(news)
        .click(offers)
        /*.typeText(firstname, 'Alejandro')
        .typeText(lastname, 'Gomez')*/
        .expect(firstname.value).contains('Alejandro')
        .expect(lastname.value).contains('Gomez')
        .typeText(company, 'Real Page')
        .typeText(address1, 'Roosvelt Ave')
        .typeText(address2, 'Richardson')
        .typeText(city, 'Queens')
        .click(state)
        .click(state.find('option').withText('New York'))
        //.expect(state.value).eql('New York')
        .typeText(postCode, '05201')
        .click(country)
        .click(country.find('option').withText('United States'))
        .typeText(other,'Register Test')
        .typeText(phone, '4455666')
        .typeText(phoneMobile, '300456789')
        .expect(alias.value).contains('My address')
        .click(registerButton)
        .wait(2000)
        .click(logOut)
        .click(logEmail)
        .typeText(logEmail, 'alejandro.gomez@rpag.com')
        .click(logPassword)
        .typeText(logPassword, 'alejo123')
        .click(login)
        .wait(5000)
}); 

//Investigar expect